version: '3.9'

services:
  mission-ros-action:
    image: mission_ros2_action
    container_name: mission_ros2_action-container
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    ports:
      - 9090:9090
      - 5000:5000
    network_mode: "bridge"